Mioto/Controllers/CarController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Mioto.Models;

namespace Mioto.Controllers
{
    public class CarController : Controller
    {
        private DB_MiotoEntities db = new DB_MiotoEntities();

        public bool IsLoggedIn { get => Session["KhachHang"] != null || Session["ChuXe"] != null; }

        List<SelectListItem> tinhThanhPho = new List<SelectListItem>
        {
            new SelectListItem { Text = "TP Hồ Chí Minh", Value = "TP Hồ Chí Minh" },
            new SelectListItem { Text = "Hà Nội", Value = "Hà Nội" },
            new SelectListItem { Text = "Đà Nẵng", Value = "Đà Nẵng" },
            new SelectListItem { Text = "Bình Dương", Value = "Bình Dương" },
            new SelectListItem { Text = "Cần Thơ", Value = "Cần Thơ" },
            new SelectListItem { Text = "Đà Lạt", Value = "Đà Lạt" },
            new SelectListItem { Text = "Nha Trang", Value = "Nha Trang" },
            new SelectListItem { Text = "Quy Nhơn", Value = "Quy Nhơn" },
            new SelectListItem { Text = "Phú Quốc", Value = "Phú Quốc" },
            new SelectListItem { Text = "Hải Phòng", Value = "Hải Phòng" },
            new SelectListItem { Text = "Vũng Tàu", Value = "Vũng Tàu" },
            new SelectListItem { Text = "Thành phố khác", Value = "Thành phố khác" },
        };

        // GET: Car/RegisterOwner
        public ActionResult RegisterOwner()
        {
            if (!IsLoggedIn)
                return RedirectToAction("Login", "Account");
            ViewBag.TinhThanhPho = tinhThanhPho;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegisterOwner(MD_ChuXe cx)
        {
            if (!IsLoggedIn)
                return RedirectToAction("Login", "Account");

            ViewBag.TinhThanhPho = tinhThanhPho;

            try
            {
                if (ModelState.IsValid)
                {
                    var guest = Session["KhachHang"] as KhachHang;
                    if (db.Xe.Any(x => x.BienSoXe == cx.BienSoXe))
                    {
                        ModelState.AddModelError("BienSoXe", "Biển số xe đã đăng ký trên hệ thống");
                        return View(cx);
                    }

                    // Lấy hoặc thêm mới ChuXe và lấy IDCX
                    var existingCX = db.ChuXe.SingleOrDefault(x => x.IDKH == guest.IDKH);
                    if (existingCX == null)
                    {
                        var newCX = new ChuXe
                        {
                            IDKH = guest.IDKH,
                            Ten = guest.Ten,
                            Email = guest.Email,
                            SDT = guest.SDT,
                            DiaChi = guest.DiaChi,
                            MatKhau = guest.MatKhau,
                            GioiTinh = guest.GioiTinh,
                            NgaySinh = guest.NgaySinh,
                            SoGPLX = guest.SoGPLX,
                            CCCD = guest.CCCD,
                            HinhAnh = guest.HinhAnh,
                            TrangThai = "Yes"
                        };
                        db.ChuXe.Add(newCX);
                        db.SaveChanges();
                        existingCX = newCX;
                    }

                    // Xử lý ảnh
                    var hinhAnhList = new List<string>();
                    foreach (string fileName in Request.Files)
                    {
                        var file = Request.Files[fileName];
                        if (file != null && file.ContentLength > 0)
                        {
                            var uploadedFileName = Path.GetFileName(file.FileName);
                            var path = Path.Combine(Server.MapPath("~/CarImages/"), uploadedFileName);
                            file.SaveAs(path);
                            hinhAnhList.Add(uploadedFileName);
                        }
                    }

                    // Lưu thông tin xe vào cơ sở dữ liệu
                    var xe = new Xe
                    {
                        IDCX = existingCX.IDCX,
                        BienSoXe = cx.BienSoXe,
                        HangXe = cx.HangXe,
                        MauXe = cx.MauXe,
                        SoGhe = cx.SoGhe,
                        TinhNang = cx.TinhNang,
                        GiaThue = cx.GiaThue,
                        NamSanXuat = cx.NamSanXuat,
                        KhuVuc = cx.KhuVuc,
                        DonGiaVanChuyen = 0,
                        TrangThai = "Sẵn sàng",
                        HinhAnh = string.Join(";", hinhAnhList)
                    };

                    db.Xe.Add(xe);
                    db.SaveChanges();
                    Session["ChuXe"] = existingCX;
                    return RedirectToAction("Home", "Home");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Có lỗi xảy ra khi lưu dữ liệu: " + ex.Message);
            }
            return View(cx);
        }

    }
}

Mioto/Views/Car/BookingCar.cshtml
@model Mioto.Models.MD_BookingCar

@{
    ViewBag.Title = "Booking Car";
    Layout = "~/Views/Shared/_LayoutBase.cshtml";
}

<h2>Booking Car</h2>

<div>
    <h4>Thông tin xe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Biển số xe</dt>
        <dd>@Model.Xe.BienSoXe</dd>

        <dt>Hãng xe</dt>
        <dd>@Model.Xe.HangXe</dd>

        <dt>Mẫu xe</dt>
        <dd>@Model.Xe.MauXe</dd>

        <dt>Số ghế</dt>
        <dd>@Model.Xe.SoGhe</dd>

        <dt>Tính năng</dt>
        <dd>@Model.Xe.TinhNang</dd>

        <dt>Giá thuê</dt>
        <dd>@Model.Xe.GiaThue</dd>

        <dt>Năm sản xuất</dt>
        <dd>@Model.Xe.NamSanXuat</dd>

        <dt>Khu vực</dt>
        <dd>@Model.Xe.KhuVuc</dd>

        <dt>Trạng thái</dt>
        <dd>@Model.Xe.TrangThai</dd>
    </dl>
</div>

<div>
    <h4>Thông tin chủ xe</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>Họ tên</dt>
        <dd>@Model.ChuXe.Ten</dd>

        <dt>Email</dt>
        <dd>@Model.ChuXe.Email</dd>

        <dt>Số điện thoại</dt>
        <dd>@Model.ChuXe.SDT</dd>

        <dt>Địa chỉ</dt>
        <dd>@Model.ChuXe.DiaChi</dd>
    </dl>
</div>

@using (Html.BeginForm("BookingCar", "Car", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.NgayThue, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.NgayThue, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.NgayThue, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.NgayTra, htmlAttributes: new { @class = "control-label" })
        @Html.EditorFor(model => model.NgayTra, new { htmlAttributes = new { @class = "form-control" } })
        @Html.ValidationMessageFor(model => model.NgayTra, "", new { @class = "text-danger" })
    </div>

    <button type="submit" class="btn btn-primary">CHỌN THUÊ</button>
}

@if (Model.ThanhToan != null && Model.ThanhToan.IDTT > 0)
{
    @Html.ActionLink("Thanh toán", "Payment", "Car", new { idtt = Model.ThanhToan.IDTT }, new { @class = "btn btn-primary" })
}

Mioto/Views/Car/RegisterOwner.cshtml
@{
    ViewBag.Title = "RegisterOwner";
    Layout = "~/Views/Shared/_LayoutBase.cshtml";
}
@model Mioto.Models.MD_ChuXe
@{ var guest = Session["KhachHang"] as Mioto.Models.KhachHang; }

<div class="modal-content" role="document" style="width: 60%;">
    <div class="modal-header">
        <h4 class="text-primary">Đăng ký xe cho thuê</h4>
        <p class="sub-title">Bạn vui lòng điền đầy đủ thông tin, MIOTO sẽ liên hệ với bạn trong vòng một ngày làm&nbsp;việc.</p>
    </div>
    <div class="modal-body">
        <div class="modal-input-body modal-owner-register">
            <div class="line-form">
                <div class="custom-input">
                    <div class="wrap-info">
                        <div class="title-status">
                            <p>Tên chủ xe*</p>
                        </div>
                    </div>
                    <div class="wrap-input disabled">
                        <div class="wrap-text">
                            <input disabled="" type="text" placeholder="@guest.Ten" value="">
                        </div>
                    </div>
                </div>
                <div class="custom-input">
                    <div class="wrap-info">
                        <div class="title-status">
                            <p>Số di động*</p>
                        </div>
                    </div>
                    <div class="wrap-input disabled">
                        <div class="wrap-text">
                            <input disabled="" type="text" placeholder="@guest.SDT" value="">
                        </div>
                    </div>
                </div>
            </div>
            @using (Html.BeginForm("RegisterOwner", "Car", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <div class="line-form">
                    <div class="custom-input">
                        <div class="wrap-info">
                            <div class="title-status">
                                <p>Khu vực cho thuê</p>
                            </div>
                        </div>
                        <div class="wrap-input">
                            @Html.DropDownListFor(model => model.KhuVuc, (IEnumerable<SelectListItem>)ViewBag.TinhThanhPho, "Chọn...", new { @class = "form-control", style = "font-size: 16px; width: 100%;" })
                            @Html.ValidationMessageFor(model => model.KhuVuc, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="line-form">
                    <div class="custom-input">
                        <div class="wrap-info">
                            <div class="title-status">
                                <p>Biển số xe*</p>
                            </div>
                        </div>
                        <div class="wrap-input">
                            @Html.TextBoxFor(model => model.BienSoXe, new { @class = "form-control", placeholder = "Biển số xe của bạn" })
                            @Html.ValidationMessageFor(model => model.BienSoXe, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="line-form">
                    <div class="custom-input">
                        <div class="wrap-info">
                            <div class="title-status">
                                <p>Hãng xe*</p>
                            </div>
                        </div>
                        <div class="wrap-input">
                            @Html.TextBoxFor(model => model.HangXe, new { @class = "form-control", placeholder = "Hãng xe của bạn" })
                            @Html.ValidationMessageFor(model => model.HangXe, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="line-form">
                    <div class="custom-input">
                        <div class="wrap-info">
                            <div class="title-status">
                                <p>Màu xe</p>
                            </div>
                        </div>
                        <div class="wrap-input">
                            @Html.TextBoxFor(model => model.MauXe, new { @class = "form-control", placeholder = "Màu xe của bạn" })
                            @Html.ValidationMessageFor(model => model.MauXe, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="custom-input">
                        <div class="wrap-info">
                            <div class="title-status">
                                <p>Số ghế</p>
                            </div>
                        </div>
                        <div class="wrap-input">
                            @Html.TextBoxFor(model => model.SoGhe, new { @class = "form-control", placeholder = "Số ghế xe của bạn" })
                            @Html.ValidationMessageFor(model => model.SoGhe, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="line-form">
                    <div class="custom-input">
                        <div class="wrap-info">
                            <div class="title-status">
                                <p>Tính năng</p>
                            </div>
                        </div>
                        <div class="wrap-input">
                            @Html.TextBoxFor(model => model.TinhNang, new { @class = "form-control", placeholder = "Tính năng xe của bạn" })
                            @Html.ValidationMessageFor(model => model.TinhNang, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="custom-input">
                        <div class="wrap-info">
                            <div class="title-status">
                                <p>Năm sản xuất</p>
                            </div>
                        </div>
                        <div class="wrap-input">
                            @Html.TextBoxFor(model => model.NamSanXuat, new { @class = "form-control", placeholder = "Năm sản xuất xe của bạn" })
                            @Html.ValidationMessageFor(model => model.NamSanXuat, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="line-form">
                    <div class="custom-input">
                        <div class="wrap-info">
                            <div class="title-status">
                                <p>Giá cho thuê xe</p>
                            </div>
                        </div>
                        <div class="wrap-input">
                            @Html.TextBoxFor(model => model.GiaThue, new { @class = "form-control", placeholder = "Giá cho thuê xe của bạn" })
                            @Html.ValidationMessageFor(model => model.GiaThue, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="line-form">
                    <div class="custom-input">
                        <div class="wrap-info">
                            <div class="title-status">
                                <p>Hình ảnh xe*</p>
                            </div>
                        </div>
                        <div class="wrap-input">
                            <input type="file" name="HinhAnh[]" class="form-control" multiple />
                            @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

                <div class="wrap-btn btn-register">
                    <button type="submit" class="btn btn--m btn-primary">Gửi thông tin đến MIOTO</button>
                </div>
            }
        </div>
    </div>
</div>